[package]
name = "glyph"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "glyph: a remote-capable terminal web browser"

[[bin]]
name = "glyph"
path = "src/main.rs"

[dependencies]
serde.workspace = true
base64 = "0.22"
serde_json.workspace = true
tempfile.workspace = true
glyph-server.workspace = true
glyph-proto.workspace = true
anyhow.workspace = true
tokio.workspace = true
clap = { version = "4", features = ["derive"] }
glyph-client.workspace = true
tracing.workspace = true
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[dev-dependencies]
tokio-tungstenite.workspace = true
futures-util.workspace = true
postcard = { version = "1", default-features = false, features = ["use-std"] }
