[package]
name = "glyph"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "glyph: a remote-capable terminal web browser"

[[bin]]
name = "glyph"
path = "src/main.rs"

[dependencies]
glyph-server.workspace = true
glyph-proto.workspace = true
anyhow.workspace = true
tokio.workspace = true
clap = { version = "4", features = ["derive"] }
glyph-client.workspace = true
tracing.workspace = true
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
